# Generated by Django 5.0.9 on 2024-10-01 22:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="")),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Three Quater", "Three Quarter"),
                            ("Double", "Double"),
                            ("Queen", "Queen"),
                            ("King", "King"),
                        ],
                        max_length=15,
                    ),
                ),
                ("number_of_beds", models.IntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Double/Twin", "Double/Twin"),
                            ("Family", "Family"),
                            ("Queen", "Queen"),
                            ("Executive", "Executive"),
                            ("Honeymoon Suite", "Honeymoon Suite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bathroom",
                    models.CharField(
                        choices=[("Ensuite", "Ensuite"), ("Shared", "Shared")],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "managed": True,
            },
        ),
    ]
