# Generated by Django 5.0.9 on 2024-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_capacity",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="room",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
