# Generated by Django 5.0.9 on 2024-10-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_room_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="can_be_rented",
            field=models.BooleanField(default=True),
        ),
    ]
