# Generated by Django 5.0.9 on 2024-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_room_can_be_rented"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
