<<<<<<< HEAD
# Generated by Django 5.0.9 on 2024-10-06 15:34
=======
# Generated by Django 5.0.9 on 2024-10-06 11:43
>>>>>>> a50589a3cc94bfe63d93cab94fb15b97633a4ad0

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

=======
>>>>>>> a50589a3cc94bfe63d93cab94fb15b97633a4ad0
    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
