# Generated by Django 5.0.9 on 2024-10-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("reservations", "0002_alter_reservation_number_of_adults_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="events",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="events_reserved", to="events.event"
            ),
        ),
    ]
