# Generated by Django 5.0.9 on 2024-10-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("reservations", "0003_alter_reservation_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="events",
            field=models.ManyToManyField(
                blank=True, related_name="events_reserved", to="events.event"
            ),
        ),
    ]
