# Generated by Django 5.0.9 on 2024-10-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_alter_reservation_events"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="total_cost",
            new_name="total_price",
        ),
        migrations.AddField(
            model_name="reservation",
            name="booking_code",
            field=models.CharField(default="ER576N", max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="guest",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_set",
                to="reservations.reservation",
            ),
        ),
    ]
