# Generated by Django 5.0.9 on 2024-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_rename_total_cost_reservation_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="booking_code",
            field=models.CharField(default="P1N8GV", max_length=6, unique=True),
        ),
    ]
