# Generated by Django 5.0.9 on 2024-10-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_alter_reservation_booking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="booking_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
